apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: assisted-events-scrape-npaz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: assisted-events-scrape-npaz
    app.kubernetes.io/part-of: assisted-events-scrape
  name: assisted-events-scrape-npaz
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: assisted-events-scrape-npaz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: assisted-events-scrape-npaz
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/assisted-events-scrape/assisted-events-scrape-npaz@sha256:e3943f5b83e6a4cad67faecfdef325e7e8f060a3d5121ae1a223922e1a2867e3
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
